RelativeURLs=true
CanonifyURLs=true
languageCode = "en-US"
defaultContentLanguage = "en"

title = "AWS IoT EduKit"
theme = "learn"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true

uglyurls = true
sectionPagesMenu = "main"
pygmentsCodeFences = true
pygmentsStyle = "monokai"

[params]
  description = "AWS IoT EduKit"
  author = "Rashed Talukder, Ryan Burke, Z Sun, Eric Fahsl"
  disableBreadcrumb = false
  disableNextPrev = false
  themeVariant = "aws"
  disableSearch = false
  disableAssetsBusting = true
  disableLanguageSwitchingButton = false
  disableShortcutsTitle = true
  disableInlineCopyToClipBoard = true

[outputs]
home = [ "HTML", "RSS", "JSON"]

[privacy.youtube]
    disable = false
    privacyEnhanced = true
[privacy.twitter]
    disable = false
    enableDNT = true
    simple = true

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[Languages]
[Languages.en]
title = "AWS IoT EduKit"
weight = 1
languageName = "English"
[Languages.de]
title = "AWS IoT EduKit"
weigth = 4
languageName = "Deutsch"
[Languages.jp]
title = "AWS IoT EduKit"
weight = 3
languageName = "日本語"
[Languages.cn]
title = "AWS IoT EduKit"
weight = 2
languageName = "简体中文"

[[Languages.en.menu.shortcuts]]
name = '<i class="fas fa-cogs"></i> Installation Instructions'
url = "/getting-started/prerequisites.html"
weight = 0

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-github'></i> Code Repository (<i class='fas fa-sync-alt fa-xs'></i> April 18, 2022)"
url = "https://github.com/m5stack/Core2-for-AWS-IoT-EduKit"
weight = 1

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-book-open'></i> Device API Reference"
url = "/api-reference/index.html"
weight = 2

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-question-circle'></i> Community Support"
url = "https://github.com/aws-samples/aws-iot-edukit-tutorials/discussions"
weight = 3

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-bug'></i> Report Bugs"
url = "https://github.com/m5stack/Core2-for-AWS-IoT-EduKit/issues"
weight = 4

[[Languages.de.menu.shortcuts]]
name = '<i class="fas fa-cogs"></i> Installationsanweisung'
url = "/getting-started/prerequisites.html"
weight = 0

[[Languages.de.menu.shortcuts]]
name = "<i class='fab fa-github'></i> Code Repository (<i class='fas fa-sync-alt fa-xs'></i> April 18, 2022)"
url = "https://github.com/m5stack/Core2-for-AWS-IoT-EduKit"
weight = 1

[[Languages.de.menu.shortcuts]]
name = "<i class='fas fa-book-open'></i> Geräte API Referenz"
url = "../en/api-reference/index.html"
weight = 2

[[Languages.de.menu.shortcuts]]
name = "<i class='fas fa-question-circle'></i> Community Support"
url = "https://github.com/aws-samples/aws-iot-edukit-tutorials/discussions"
weight = 3

[[Languages.de.menu.shortcuts]]
name = "<i class='fas fa-bug'></i> Fehler melden"
url = "https://github.com/m5stack/Core2-for-AWS-IoT-EduKit/issues"
weight = 4

[blackfriday]
  hrefTargetBlank = true

[menu]
  [[menu.main]]
    identifier = " "
    name = " "
    title = " "
    url = "/"
    weight = -110

[[menu.shortcuts]]
name = "<i class='fab fa-github'></i> Code Repository (<i class='fas fa-sync-alt fa-xs'></i> April 18, 2022)"
url = "https://github.com/m5stack/Core2-for-AWS-IoT-EduKit"
weight = 1

[[menu.shortcuts]]
name = "<i class='fas fa-book-open'></i> Device API Reference"
url = "https://edukit.workshop.aws/en/api-reference/index.html"
hrefTargetBlank = true
weight = 2

[[menu.shortcuts]]
name = "<i class='fas fa-question-circle'></i> Community Support"
url = "https://github.com/aws-samples/aws-iot-edukit-tutorials/discussions"
weight = 3

[[menu.shortcuts]]
name = "<i class='fas fa-bug'></i> Report Bugs"
url = "https://github.com/m5stack/Core2-for-AWS-IoT-EduKit/issues"
weight = 4
